name: Run unit test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.11-management
        ports:
          - 1883:1883
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "8.0"
      - uses: php-actions/phpunit@v3
        with:
          php_version: "8.0"
          version: "9"
          configuration: "./phpunit.xml"
